In [1]:
import torch
import numpy as np

In [2]:
pe = torch.zeros(50, 512)
pe

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [3]:
pe.shape

torch.Size([50, 512])

In [5]:
pe[:, 0::2].shape

torch.Size([50, 256])

# Unsqueeze()

Unsqueeze() 함수는 PyTorch 텐서에 새로운 차원을 추가하는 메서드입니다. 이 함수는 지정된 위치에 크기가 1인 새 차원을 삽입합니다. 이는 텐서의 형상을 변경하는 데 유용하며, 특히 브로드캐스팅이나 특정 연산에 필요한 차원을 추가할 때 자주 사용됩니다.

In [6]:
import torch

# 1차원 텐서 생성
a = torch.tensor([1, 2, 3, 4])
print("Original tensor a:")
print(a)
print("Shape of a:", a.shape)

# 0번 인덱스에 차원 추가
b = a.unsqueeze(0)
print("\nAfter a.unsqueeze(0):")
print(b)
print("Shape of b:", b.shape)

# 1번 인덱스에 차원 추가
c = a.unsqueeze(1)
print("\nAfter a.unsqueeze(1):")
print(c)
print("Shape of c:", c.shape)

# 2차원 텐서 생성
d = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("\nOriginal 2D tensor d:")
print(d)
print("Shape of d:", d.shape)

# 0번 인덱스에 차원 추가
e = d.unsqueeze(0)
print("\nAfter d.unsqueeze(0):")
print(e)
print("Shape of e:", e.shape)

# 2번 인덱스에 차원 추가
f = d.unsqueeze(2)
print("\nAfter d.unsqueeze(2):")
print(f)
print("Shape of f:", f.shape)

Original tensor a:
tensor([1, 2, 3, 4])
Shape of a: torch.Size([4])

After a.unsqueeze(0):
tensor([[1, 2, 3, 4]])
Shape of b: torch.Size([1, 4])

After a.unsqueeze(1):
tensor([[1],
        [2],
        [3],
        [4]])
Shape of c: torch.Size([4, 1])

Original 2D tensor d:
tensor([[1, 2, 3],
        [4, 5, 6]])
Shape of d: torch.Size([2, 3])

After d.unsqueeze(0):
tensor([[[1, 2, 3],
         [4, 5, 6]]])
Shape of e: torch.Size([1, 2, 3])

After d.unsqueeze(2):
tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]]])
Shape of f: torch.Size([2, 3, 1])


In [10]:
d = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(d.shape)  # torch.Size([2, 3])
d

torch.Size([2, 3])


tensor([[1, 2, 3],
        [4, 5, 6]])

In [19]:
d.unsqueeze(2)

tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]]])