In [1]:
import torch
import numpy as np

In [2]:
pe = torch.zeros(50, 512)
pe

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [3]:
pe.shape

torch.Size([50, 512])

In [5]:
pe[:, 0::2].shape

torch.Size([50, 256])

# Unsqueeze()

Unsqueeze() 함수는 PyTorch 텐서에 새로운 차원을 추가하는 메서드입니다. 이 함수는 지정된 위치에 크기가 1인 새 차원을 삽입합니다. 이는 텐서의 형상을 변경하는 데 유용하며, 특히 브로드캐스팅이나 특정 연산에 필요한 차원을 추가할 때 자주 사용됩니다.

In [6]:
import torch

# 1차원 텐서 생성
a = torch.tensor([1, 2, 3, 4])
print("Original tensor a:")
print(a)
print("Shape of a:", a.shape)

# 0번 인덱스에 차원 추가
b = a.unsqueeze(0)
print("\nAfter a.unsqueeze(0):")
print(b)
print("Shape of b:", b.shape)

# 1번 인덱스에 차원 추가
c = a.unsqueeze(1)
print("\nAfter a.unsqueeze(1):")
print(c)
print("Shape of c:", c.shape)

# 2차원 텐서 생성
d = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("\nOriginal 2D tensor d:")
print(d)
print("Shape of d:", d.shape)

# 0번 인덱스에 차원 추가
e = d.unsqueeze(0)
print("\nAfter d.unsqueeze(0):")
print(e)
print("Shape of e:", e.shape)

# 2번 인덱스에 차원 추가
f = d.unsqueeze(2)
print("\nAfter d.unsqueeze(2):")
print(f)
print("Shape of f:", f.shape)

Original tensor a:
tensor([1, 2, 3, 4])
Shape of a: torch.Size([4])

After a.unsqueeze(0):
tensor([[1, 2, 3, 4]])
Shape of b: torch.Size([1, 4])

After a.unsqueeze(1):
tensor([[1],
        [2],
        [3],
        [4]])
Shape of c: torch.Size([4, 1])

Original 2D tensor d:
tensor([[1, 2, 3],
        [4, 5, 6]])
Shape of d: torch.Size([2, 3])

After d.unsqueeze(0):
tensor([[[1, 2, 3],
         [4, 5, 6]]])
Shape of e: torch.Size([1, 2, 3])

After d.unsqueeze(2):
tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]]])
Shape of f: torch.Size([2, 3, 1])


In [10]:
d = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(d.shape)  # torch.Size([2, 3])
d

torch.Size([2, 3])


tensor([[1, 2, 3],
        [4, 5, 6]])

In [19]:
d.unsqueeze(2)

tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]]])

# View()

- 텐서의 형상을 변경

- 전체 요소의 수는 바뀌지 않는다.

- 메모리 레이아웃을 변경하지 않고 텐서를 재해석합니다.

In [20]:
import torch 

# 3x4 텐서 생성 

x = torch.tensor([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]]) 

print("Original tensor x:" , x.shape)

Original tensor x: torch.Size([3, 4])


In [21]:
y = x.view(2, 6)

print("\nAfter x.view(2, 6):", y.shape) 
print(y)
print("\nOriginal tensor x:" , x.shape)
print("New tensor y:" , y.shape)    


After x.view(2, 6): torch.Size([2, 6])
tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])

Original tensor x: torch.Size([3, 4])
New tensor y: torch.Size([2, 6])


In [22]:
# 1차원으로 펼치기
z = x.view(-1)
print("After view(-1):")
print(z)
print("New shape:", z.shape) 

After view(-1):
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
New shape: torch.Size([12])


# transpose()

- 지정된 두 차원의 순서를 바꿉니다.

- 메모리 레이아웃을 변경할 수 있다.

In [23]:
import torch

# 2x3x4 텐서 생성
x = torch.tensor([[[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]],
                  [[13, 14, 15, 16],
                   [17, 18, 19, 20],
                   [21, 22, 23, 24]]])

print("Original shape:", x.shape)  # 출력: torch.Size([2, 3, 4])

# 첫 번째와 두 번째 차원 교환
y = x.transpose(0, 1)
print("After transpose(0, 1):")
print(y)
print("New shape:", y.shape)  # 출력: torch.Size([3, 2, 4])

# 두 번째와 세 번째 차원 교환
z = x.transpose(1, 2)
print("After transpose(1, 2):")
print(z)
print("New shape:", z.shape)  # 출력: torch.Size([2, 4, 3])

Original shape: torch.Size([2, 3, 4])
After transpose(0, 1):
tensor([[[ 1,  2,  3,  4],
         [13, 14, 15, 16]],

        [[ 5,  6,  7,  8],
         [17, 18, 19, 20]],

        [[ 9, 10, 11, 12],
         [21, 22, 23, 24]]])
New shape: torch.Size([3, 2, 4])
After transpose(1, 2):
tensor([[[ 1,  5,  9],
         [ 2,  6, 10],
         [ 3,  7, 11],
         [ 4,  8, 12]],

        [[13, 17, 21],
         [14, 18, 22],
         [15, 19, 23],
         [16, 20, 24]]])
New shape: torch.Size([2, 4, 3])


# MHA 에서의 사용 


In [24]:
# 가정: batch_size=32, seq_len=10, d_model=512, num_heads=8
query = torch.randn(32, 10, 512)
d_k = 512 // 8  # 64

# view를 사용한 reshape
reshaped = query.view(32, 10, 8, 64)
print("After view:", reshaped.shape)  # 출력: torch.Size([32, 10, 8, 64])

# transpose를 사용한 차원 교환
transposed = reshaped.transpose(1, 2)
print("After transpose:", transposed.shape)  # 출력: torch.Size([32, 8, 10, 64])

After view: torch.Size([32, 10, 8, 64])
After transpose: torch.Size([32, 8, 10, 64])


# einops의 rearrange()

기본 구문 : rearrange(tensor, pattern, **axes_lengths)

'h w -> w h'는 높이(h)와 너비(w)의 순서를 바꿉니다.


이는 transpose(0, 1)와 동일한 효과를 가집니다.

In [29]:
import torch
from einops import rearrange

# 2x3 텐서 생성
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

# 'h w -> w h' 패턴으로 변환
y = rearrange(x, 'h w -> w h')

print("Original:")
print(x)
print("Rearranged:")
print(y)

Original:
tensor([[1, 2, 3],
        [4, 5, 6]])
Rearranged:
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [30]:
import torch
from einops import rearrange

# 입력 텐서 생성 (batch_size=2, seq_len=4, d_model=6)
x = torch.randn(2, 4, 6)

# Multi-Head Attention을 위한 변환 (3개의 헤드 사용)
y = rearrange(x, 'b s (h d) -> b h s d', h=3)

print("Original shape:", x.shape)
print("Rearranged shape:", y.shape)
print("\nOriginal first batch:")
print(x[0])
print("\nRearranged first batch:")
print(y[0])

Original shape: torch.Size([2, 4, 6])
Rearranged shape: torch.Size([2, 3, 4, 2])

Original first batch:
tensor([[ 0.4128, -1.6735, -0.7718, -0.1332, -1.2515, -0.9798],
        [ 0.1550,  0.0801, -0.4636,  0.4807, -0.8876, -0.1907],
        [ 0.7108,  0.6153, -1.6800,  0.6584,  0.4997,  1.6443],
        [ 1.3176,  0.3500, -2.1003, -1.1443,  0.5477,  0.7834]])

Rearranged first batch:
tensor([[[ 0.4128, -1.6735],
         [ 0.1550,  0.0801],
         [ 0.7108,  0.6153],
         [ 1.3176,  0.3500]],

        [[-0.7718, -0.1332],
         [-0.4636,  0.4807],
         [-1.6800,  0.6584],
         [-2.1003, -1.1443]],

        [[-1.2515, -0.9798],
         [-0.8876, -0.1907],
         [ 0.4997,  1.6443],
         [ 0.5477,  0.7834]]])


In [32]:
# 차원 축소
z = rearrange(x, 'b s d -> b (s d)')

# 새 차원 추가
w = rearrange(x, 'b s d -> b s d 1')

# 반복
v = rearrange(x, '(b rep) s d -> b rep s d', rep=2)

v

tensor([[[[ 0.4128, -1.6735, -0.7718, -0.1332, -1.2515, -0.9798],
          [ 0.1550,  0.0801, -0.4636,  0.4807, -0.8876, -0.1907],
          [ 0.7108,  0.6153, -1.6800,  0.6584,  0.4997,  1.6443],
          [ 1.3176,  0.3500, -2.1003, -1.1443,  0.5477,  0.7834]],

         [[-0.2334,  0.0522,  0.0320, -0.6319, -0.7109,  0.1886],
          [ 1.3602, -1.3268,  0.2144, -0.7237,  1.0461, -0.4960],
          [ 0.3507,  0.0525,  0.5012, -0.5611, -0.0548, -0.6728],
          [ 0.9347,  1.3708, -0.9378,  1.0910, -0.3654, -0.5567]]]])